-- OMNAI Console · admin_audit_log ganha id numérico estável (seq) para o
-- admin-get-audit conformar ao contrato Bloco 2 (AuditEntry.id: number).
-- Aplicada a prod (stoa) em 06-08-2026 como migration `omnai_console_admin_audit_seq`.
alter table public.admin_audit_log
  add column if not exists seq bigint generated by default as identity;

create index if not exists admin_audit_log_tenant_seq_idx
  on public.admin_audit_log (tenant_id, seq desc);
